name: Docker_Pipeline

on: 
  push

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v3
    - name: build and push the image
      run: |
         docker login —username ikeokoli —password ${{ secrets.GH_PAT }} ghcr.io
         docker build . —tag ghcr.io/ikeokoli/my-python-image:latestversion3
         docker push ghcr.io/ikeokoli/my-python-image:latestversion3
    
      
